### ISSUE TITLE
implementation of `slogdet` in eagerpy

### ISSUE THREAD

**Issue by eserie** [jonasrauber/eagerpy#27]
Would you consider to add or accept a contribution to add and implementation of `slogdet` function (see for ex the [numpy implementation)](https://numpy.org/doc/stable/reference/generated/numpy.linalg.slogdet.html)?

**Comment by jonasrauber** [comment]
Sure. How do you intend to implement that in PyTorch and TensorFlow?

**Comment by eserie** [comment]
Here are the implementatins for [pytorch](https://pytorch.org/docs/stable/generated/torch.slogdet.html), [tesnorflow](https://www.tensorflow.org/api_docs/python/tf/linalg/slogdet) and [jax](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.slogdet.html).

**Comment by jonasrauber** [comment]
Sounds good, feel free to open a PR

**Comment by eserie** [comment]
Ok, thanks @jonasrauber, I'm catching the development workflow and I should soon propose a PR on which we should iterate to accommodate style, testing etc...

**Comment by eserie** [comment]
Hi @jonasrauber, I proposed the PR #28. Let me know if you think something should be done differently. Thanks.
