### ISSUE TITLE
Clarify copyright and license

### ISSUE THREAD

**Issue by gspr** [jonasrauber/eagerpy#8]
I'm considering packaging EagerPy for Debian. I think that effort may encounter some hurdles due to missing copyright notices and unclear licensing. As far as I can tell (please forgive me if I've overlooked something), the license is only specified in `setup.py`, and even there just given as "MIT License". It would be of great help if you could add a `LICENSE` fle where you clearly state your copyright over the code and the full licensing terms (for example the full terms of the MIT license).

It would be even more helpful if a copyright notice were added to each source file, but I understand if this is too much of a hassle.

**Comment by jonasrauber** [comment]
Plan to do this soon. Could you explain what it means to package this for Debian? What's the purpose?

**Comment by gspr** [comment]
Jonas Rauber <notifications@github.com> writes:

> Plan to do this soon. Could you explain what it means to package this
> for Debian? What's the purpose?

I'm happy to explain, but I'm a bit confused about what you mean. Do you
know how Linux distributions work?

**Comment by gspr** [comment]
Jonas Rauber <notifications@github.com> writes:

> Plan to do this soon. Could you explain what it means to package this
> for Debian? What's the purpose?

The purpose would be to make EagerPy part of Debian's packaging system
[1] so that users of Debian and derived distributions can install
EagerPy with "apt get install python3-eagerpy", and so that other Debian
packages already in Debian can depend on it. It is the latter that is my
primary motivation; I'm the maintainer of GUDHI in Debian, and while its
dependence on EagerPy is optional, I'd like to make it available.

[1] https://www.debian.org/distrib/packages

**Comment by jonasrauber** [comment]
I see. Thanks for the explanation. Great to see other people using EagerPy 👍 
I've now decided on a license and added it to the repository (MIT license).
